version: "3.2"

services:
  ripeti-db:
    build:
      context: .
      dockerfile: pg-Dockerfile
    volumes:
      - ripeti_db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ripeti
      POSTGRES_USER: ripeti
      POSTGRES_PASSWORD: password
    restart: on-failure
    networks:
      - ripeti-network
    ports:
      - 5434:5432
    command: ["postgres", "-c", "log_statement=all"]
  postgres-keycloak:
    image: postgres
    volumes:
      - keycloak_db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    restart: on-failure
    networks:
      - ripeti-network
    ports:
      - 5433:5432
  keycloak:
    image: quay.io/keycloak/keycloak:9.0.0
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres-keycloak
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
      KEYCLOAK_LOGLEVEL: ALL
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      JDBC_PARAMS: "ssl=false"
    ports:
      - 8884:8080
    depends_on:
      - postgres-keycloak
    networks:
      - ripeti-network
    restart: on-failure
networks:
  ripeti-network:
    driver: bridge

volumes:
  ripeti_db: {}
  keycloak_db: {}
